### ISSUE TITLE
NaN in .csv files

### ISSUE THREAD

**Issue by f-amerehi** [bethgelab/model-vs-human#28]
Hi @rgeirhos, Hope all is well

I've added a new model in `model_zoo.py`, it returns a resnet50 with a custom checkpoint.
Now in my CSVs I see some `NaN`s in the "rt" column, is it ok to have these NaN numbers?

```
subj,session,trial,rt,object_response,category,condition,imagename
resnet50d,1,1,NaN,clock,airplane,NaN,airplane1.png
resnet50d,1,2,NaN,knife,airplane,NaN,airplane10.png
resnet50d,1,3,NaN,clock,airplane,NaN,airplane2.png
resnet50d,1,4,NaN,knife,airplane,NaN,airplane3.png
resnet50d,1,5,NaN,clock,airplane,NaN,airplane4.png
...
```

I am wondering why do we have NaN in https://github.com/bethgelab/model-vs-human/blob/d78bcfc94374faee19b3ad43ba2fd17364b00e1c/modelvshuman/evaluation/evaluate.py#L149

thanks

**Comment by rgeirhos** [comment]
The corresponding column is "rt" which stands for "response time", this column only makes sense for human data thus all models have a NaN here - as intended.

However, the model's accuracies on the five samples you posted here seems to be 0% thus there might be a problem somewhere.

**Comment by f-amerehi** [comment]
Thanks for your quick answer
What about NaN in "condition"?

How did you detect that accuracies is 0 in the samples? should I check anything, because the original accuracy is around 80

Here are my changes, I changed the code to be able to load checkpoints
https://github.com/f-amerehi/model-vs-human/commit/751e8fe55ae76f7f70ec62cdad3d2f1f24de8055

Do you see any bug there?

**Comment by rgeirhos** [comment]
NaN in "condition" is also expected for some datasets, like e.g. "edge" which does not have different conditions. The column is only relevant for datasets with multiple conditions, like different levels of noise.

The accuracy is low since "object_response" (= the model's prediction) does not match "category" (ground truth category). You should be able to verify the pipeline by running one of the example models like a standard ResNet-50. As a sanity check, models should reach high accuracy on the "colour" dataset which consists of natural colored and greyscale images.

**Comment by f-amerehi** [comment]
Thank you @rgeirhos very much. Have a nice weekend.
